on:
  pull_request:
    branches:
    - main
jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Setup
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3.8.1
      with:
        node-version: 18
    - name: lint
      run: yarn lint
    - name: build
      run: yarn build
